# CAMA 2022 second chance

Here is the subject, the answers must be written in the Moodle.

You also have an `ipynb` version of the subject so that you can write your answers as you go along
copy the complete answers with their dependencies in the Moodle.

#### Rules

* You should not do any `import`.  `import numpy as np` is already done globally.
* You should not use `linalg`
* No `if`, `while` or` for` unless it says you can.
* No recursion.

I verify the prohibitions by a search in your code. If I find it, it's 0. So don't take variable names that include forbidden words.

## Problem

Let be a vector $\bf v$, we define the matrix T as follows:

$$T =  Id - 2 \, \frac{{\bf v}\,{\bf v}^T}{||{\bf v}||^2} \quad \quad (1)$$

With $Id$ the identity matrix.

Let be a matrix A. We define `c0 = A[:, 0]`.

We pose

$$ {\bf v_0} = {\bf c_0} - 
\begin{bmatrix}
|| {\bf c_0} || \\
0 \\
\vdots \\
0
\end{bmatrix}
$$

We thus obtain
$$T_0 =  Id - 2 \, \frac{{\bf v_0}\,{\bf v_0}^T}{||{\bf v_0}||^2}$$

* Take a random 5x5 matrix A.

In [133]:
import numpy as np
A = np.random.rand(5, 5)
print(A)
c = 1
#print(A[3:5, 3:5])

[[0.61219313 0.69378367 0.77945471 0.14334431 0.83201333]
 [0.3802645  0.71282613 0.7714887  0.4718956  0.23969207]
 [0.89210066 0.80997549 0.99828359 0.74780678 0.85694778]
 [0.54954485 0.01845068 0.32660706 0.16056691 0.93154366]
 [0.90644717 0.90723898 0.7932067  0.51737412 0.82397993]]


* Calculate $T_0$ and verify that $T_0 \, A$ puts zeros in the first column except the first line.

In [89]:

def findNorm(v):
    return np.sqrt(sum(np.square(v)))

def calcv0(A):
    c0 = A[:, 0]
    norm_c0 = findNorm(c0)
    x = np.zeros(5)
    x[0] = norm_c0
    return c0 - x

def calcT0(A):
    id = np.identity(5)
    v0 = calcv0(A)
    t0 = id - 2 * (np.dot(v0[:, None], v0[None, :]) / sum(np.square(v0)))
    return np.matmul(t0, A)

Res = calcT0(A)
print(Res)





[[ 6.08276253  9.69954025  4.60317164  6.24716152 11.50792911]
 [ 0.         -0.86039121  5.80167838 -0.73886216  2.87381217]
 [ 0.          1.13960879  0.80167838  5.26113784  5.87381217]
 [ 0.         -0.15097804 -0.49580404  2.15284461  0.18453041]
 [ 0.          3.13960879  6.80167838  2.26113784 -3.12618783]]


We call `Res` the result of $T_0 \, A$.

* Taking `c1` as the part below the diagonal of the 2nd column (including the diagonal) of` Res`, calculate $T_1$. This matrix is smaller in size than $T_0$.
* Compute multiplication $T_1$`Res [1 :, 1:]` and check that the new `Res` has zeros under the diagonal strictly for the first 2 columns.

In [94]:
def calcv1(Res, c):
    c1 = Res[c:,c]
    norm_c1 = findNorm(c1)
    x = np.zeros(len(c1))
    x[0] = norm_c1
    return c1 - x
def calcT1(Res, c):
    v1 = calcv1(Res, c)
    id = np.identity(len(v1))
    t1 = id - 2 * (np.dot(v1[:, None], v1[None, :]) / sum(np.square(v1)))
    return t1 @ Res[1 :, 1:]
    
print(calcT1(Res, 1))

[[ 3.45237873e+00  5.02591190e+00  3.88294751e+00 -1.62833283e+00]
 [ 1.11022302e-16  1.00666736e+00  4.03986823e+00  7.06346152e+00]
 [-2.77555756e-17 -5.22961457e-01  2.31464127e+00  2.69228855e-02]
 [ 4.44089210e-16  7.36642061e+00 -1.10344557e+00  1.51282130e-01]]


* As T1 is smaller, as well as the $T_i$ which follow, write the function `resize_mat(T, n)` which enlarges $T$
so that it is of size $n \times n$ with 1 on the diagonal in the top left and T in the bottom right.
For example for $T_2$ we have:

$$
\hat{T_2} = 
\begin{bmatrix}
\begin{array}{cc}
1 & 0  \\
0 & 1 
\end{array}  & 0 \\
0 & {\Huge T_2}
\end{bmatrix}
$$

In [113]:
def resize_mat(T, n):
    id = np.identity(n)
    id[n-len(T): n, n-len(T[0]):n] = T
    return id

print(resize_mat(Res, 6))


[[ 1.          0.          0.          0.          0.          0.        ]
 [ 0.          6.08276253  9.69954025  4.60317164  6.24716152 11.50792911]
 [ 0.          0.         -0.86039121  5.80167838 -0.73886216  2.87381217]
 [ 0.          0.          1.13960879  0.80167838  5.26113784  5.87381217]
 [ 0.          0.         -0.15097804 -0.49580404  2.15284461  0.18453041]
 [ 0.          0.          3.13960879  6.80167838  2.26113784 -3.12618783]]


### Question 1

Indicate the property(s) of the $\hat{T_{n-1}} \, \hat{T_{n-2}} \, \dots \, \hat{T_1} \, T_0 \, A$ matrix. It is

* Triangular
* Tri-diagonal
* Symmetrical
* Orthogonal

### Question 2

Write the function `compute_T(A, i)` which returns $T$ as it is defined in (1) with $i$ the i-th column of the matrix A. Attention you must only take what is below the diagonal , diagonal included so T is equal to or smaller than A.

In [154]:
def calcVi(A, i):
    c = A[i:, i]
    norm_c = findNorm(c)
    x = np.zeros(len(c))
    x[0] = norm_c
    return c - x

def compute_T(A, i):
    v = calcVi(A, i)
    id = np.identity(len(v))
    t = id - 2 * (np.dot(v[:, None], v[None, :]) / sum(np.square(v)))
    return t

T = compute_T(A, 0)
Res = T @ A
Res = compute_T(Res, 1) @ Res[1:,1:]
    


[[ 6.25754867e-01  4.19733648e-01  2.19449120e-01 -3.42968802e-01]
 [ 1.38777878e-17  1.94510293e-01 -5.16864179e-02  1.83322096e-01]
 [-4.16333634e-17 -1.85538638e-01 -1.67517215e-01 -3.34072867e-02]
 [ 2.77555756e-17 -2.05103309e-02 -3.23799798e-01  2.35940411e-01]]


### Question 3

Test different cases and indicate the property or properties of the matrices returned by `compute_T`.

* Triangular
* Tri-diagonal
* Symmetrical
* Orthogonal

### Question 4

Write the function `solve(A, b)` which returns **x** solution of the $A {\bf x} = {\bf b}$ matrix system
using the `compute _T` method. The function must work for any size $n \times n$ of matrix A.

You can use **2** `for` loops. It is not necessary to use `resize_ mat` to write this function.

In [169]:


def solve_gauss(A, b):
    A = A.astype(np.float64)   # si A a des entiers, on va avoir des erreurs de calculs
    for i in range(len(A)-1):
        coefs = - A[i+1:,i] / A[i,i]  # Normalement il faut tester que A[i,i] != 0
        A[i+1:, i:] += np.outer(coefs, A[i, i:]) # ou np.einsum('i,j -> ij', coefs, A[i, i:])
        b[i+1:] += coefs * b[i]                  # multiplication terme à terme
    # A est maintenant triangulaire surpérieur
    res = np.zeros(len(b), dtype=b.dtype)
    res[-1] = b[-1] / A[-1,-1]
    for i in range(len(A)-1)[::-1]:
        res[i] = (b[i] - A[i,i+1:] @ res[i+1:]) / A[i,i]
    return res

def solve1(A, b):
    Res = A
    Resb = b
    for i in range(len(A) - 1):
        T = compute_T(Res, i)
        Res = resize_mat(T, len(Res)) @ Res
        Resb = resize_mat(T, len(Resb)) @ Resb
    return solve_gauss(Res, Resb)
A = A = np.array([[1.,1,1],[2,1,2],[-1,0,3]])

solve1(A, np.ones(3))

array([-0.25,  1.  ,  0.25])

### Question 5

Write the function `decompose(A)` which returns 2 matrices:

* the $T_{n-1} \, T_{n-2} \, \dots \, T_1 \, T_0 \, A$ result with the remark made above
* the inverse of the set of transformations made at A

So if `decompose` returns U and V then $A = V \, U$.

You can use **1** `for` loop. It is necessary to use `resize_mat` for this write this function.

In [179]:
def aux(A):
    Res = A
    V = np.identity(len(A))
    for i in range(len(A) - 1):
        T = compute_T(Res, i)
        Res = resize_mat(T, len(Res)) @ Res
        V = resize_mat(T, len(V)) @ V
    return Res, V

def decompose(A):
    U, V  = aux(A)
    return U, V.T

U, V = decompose(A)
print(A)
print(np.max(np.abs(A - V @ U) < 1E-5))



[[ 1.  1.  1.]
 [ 2.  1.  2.]
 [-1.  0.  3.]]
True


### Question 6

Indicate the property (ies) of my matrix V (2nd matrix returned by `decompose`):

* Triangular
* Tri-diagonal
* Symmetrical
* Orthogonal